spring:
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

management:
  health:
    mail:
      enabled: false

attachment-store:
  url: http://${ATTACHMENT_STORE_SERVICE_SERVICE_HOST}:8080
  read-timeout: 1000ms
  connect-timeout: 1000ms

authenticator:
  url: http://${AUTHENTICATOR_SERVICE_SERVICE_HOST}:8080
  read-timeout: 1000ms
  connect-timeout: 1000ms

user-details-manager-client:
  url: http://${USER_DETAILS_MANAGER_SERVICE_SERVICE_HOST}:8080
  read-timeout: 1000ms
  connect-timeout: 1000ms
