server:
  shutdown: immediate

spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: localhost
    port: ${green-mail-port}
    username: spring
    password: boot
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
