spring:
  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          writetimout: 5000
          timeout: 5000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.mail.MailException
        - java.io.IOException
      ignoreExceptions: []
    attachmentStore:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableAttachmentStoreClientException
      ignoreExceptions: [ ]
    authenticator:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableAuthenticatorClientException
      ignoreExceptions: [ ]
    userDetailsManager:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableUserDetailsManagerClientException
      ignoreExceptions: [ ]

attachment-store:
  read-timeout: 1000ms
  connect-timeout: 1000ms
  
authenticator:
  read-timeout: 1000ms
  connect-timeout: 1000ms

user-details-manager-client:
  read-timeout: 1000ms
  connect-timeout: 1000ms
